#!/opt/bin/sh
#title           :service
#description     :Managing services in entware
#author          :Pavel P.
#TG              :@pnpzx

service() {

  local showPrefix showRC showColors pathServices listServices getPrefix green red white yellow reset editor

  # show prefix, ex S01,K02... etc
  # 1 - show, 0 - disable
  showPrefix=1
  # show rc.unslung in service list
  showRC=0
  # output color
  # 1 - color, 0 - whitout color
  showColors=1

  #green='\e[32m'
  #red='\e[31m'
  #white='\e[37m'
  #yellow='\e[33m'
  #reset='\e[0m'
  green="\033[1;32m";
  red="\033[1;31m";
  white="\033[1;37m";
  yellow="\033[1;33m";
  reset="\033[m";

  pathServices="/opt/etc/init.d"

  if [ "$showPrefix" -gt 1 ]; then
    echo -e "\nVariable showPrefix must be 0 or 1\n"
    return 255
  fi
  if [ "$showRC" -gt 1 ]; then
    echo -e "\nVariable showRC must be 0 or 1\n"
    return 255
  fi
  if [ "$showColors" -gt 1 ]; then
    echo -e "\nVariable showColors must be 0 or 1\n"
    return 255
  fi

  if [ "$showRC" -eq 1 ]; then
    listServices="$(ls -1 $pathServices/[A-Z][0-9]* $pathServices/rc.uns* | sed 's,.*/,,')"
  else
    listServices="$(ls -1 $pathServices/[A-Z][0-9]* | sed 's,.*/,,')"
  fi

  [ -n "$1" ] && \
    #getPrefix=$(echo -e "$listServices\n" | grep "^[A-Z].{2}${1}$" | grep -Eo '^[A-Z].{2}')
    #getPrefix=$(echo -e "$listServices\n" | grep -E "^[A-Z][0-9]{2}${1}$" | cut -c1-3)
    getPrefix=$(echo -e "$listServices\n" | grep -E "^[A-Z][0-9]{2}${1}$" | sed 's/^\(...\).*/\1/')

  _printServicesList() {
    if [ "$showPrefix" -eq 1 ]; then
      if [ "$showColors" -eq 1 ]; then
        echo -e "$listServices\n" | sed "/S/s,^\(\), $(echo -e ${green}),;/[A-R,T-Z]/s,^\(\), $(echo -e ${red}),;s,$,$(echo -e ${reset}),;s,[A-Z][0-9][0-9],& | ,g"
      else
         echo -e "$listServices\n" | sed "/S/s,^\(\), ,;/[A-R,T-Z]/s,^\(\), ,;s,[A-Z][0-9][0-9],& | ,g"
      fi
    else
      if [ "$showColors" -eq 1 ]; then
        echo -e "$listServices\n" | sed "/S/s,^\(...\), $(echo -e ${green}),;/[A-R,T-Z]/s,^\(...\), $(echo -e ${red}),;s,$,$(echo -e ${reset}),"
      else
        echo -e "$listServices\n" | sed "/S/s,^\(...\), ,;/[A-R,T-Z]/s,^\(...\), ,;s,[A-Z][0-9][0-9],& | ,g"
      fi
    fi
  }

  _printTextAvailable() {
    echo -e ""
    if [ "$showColors" -eq 1 ]; then
      if [ "$showPrefix" -eq 1 ]; then
        echo -e " The following services are available:\n (prefixes: ${red}A-R${reset},${red}T-Z${reset} disabled, ${green}S${reset} - enabled)"
      else
        echo -e " The following services are available:\n (${red}RED${reset} - disabled, ${green}GREEN${reset} - enabled)"
      fi
    else
      if [ "$showPrefix" -eq 1 ]; then
        echo -e " The following services are available:\n (prefixes: A-R,T-Z - disabled, S - enabled)"
      else
        echo -e " The following services are available:"
      fi
    fi
  }

  _printTextNotFound() {
    echo -e ""
    if [ "$showColors" -eq 1 ]; then
      echo -e " Service ${red}$1${reset} NOT FOUND" && echo -e ""
      if [ "$showPrefix" -eq 1 ]; then
        echo -e " The following services are available:\n (prefixes: ${red}A-R${reset},${red}T-Z${reset} disabled, ${green}S${reset} - enabled)"
      else
        echo -e " The following services are available:\n (${red}RED${reset} - disabled, ${green}GREEN${reset} - enabled)"
      fi
    else
      echo -e " Service $1 NOT FOUND" && echo -e ""
      if [ "$showPrefix" -eq 1 ]; then
        echo -e " The following services are available\n (prefixes: A-R,T-Z - disabled, S - enabled)"
      else
        echo -e " The following services are available:"
      fi
    fi
  }

   _printTextAdditionCommand() {
    me="$(basename $(test -L "$0" && readlink "$0" || echo "$0"))"
    if [ -z "$1" ]; then
      if [ "$showColors" -eq 1 ]; then
        echo -e " Service Startup Management: ${yellow}$me ${reset}<service_name> {${green}edit${reset}|${green}disable${reset}|${green}enable${reset}}\n"
      else
        echo -e " Service Startup Management: $me <service_name> {edit|disable|enable}\n"
      fi
    else
      if [ "$showColors" -eq 1 ]; then
        echo -e " Service Startup Management: ${yellow}$me ${reset}$1 {${green}edit${reset}|${green}disable${reset}|${green}enable${reset}}\n"
      else
        echo -e " Service Startup Management: $me $1 {edit|disable|enable}\n"
      fi
    fi
   }

  _control() {
    if [ $# -eq 1 ]; then
      "$pathServices/${getPrefix}$1" | sed "s,$pathServices/${getPrefix}$1,service $1,"
       echo -e ""
       _printTextAdditionCommand "$1"
    else
      "$pathServices/${getPrefix}$@" | sed "s,$pathServices/${getPrefix}$1,service $1,"
    fi
   return 0
  }

  if [ "$1" = "edit" ]; then
    if [ -n "$(which nano)" ]; then
      editor="nano"
      $editor "$0"
      return 0
    elif [ -n "$(which vi)" ]; then
      editor="busybox vi"
      $editor "$0"
      return 0
    else
      echo -e "\nEDITOR: vi or nano NOT FOUND\n"
      return 255
    fi
  fi

  if [ -z "$1" ]; then
    _printTextAvailable
    _printServicesList
    _printTextAdditionCommand
    return 0
  fi

  if [ ! -e "$pathServices/${getPrefix}$1" ]; then
    _printTextNotFound "$1"
    _printServicesList
    _printTextAdditionCommand
    return 255
  fi

  if [ -n "$2" ]; then
    if [ "$2" = "disable" ]; then
      toPrefixDis=$(echo "$getPrefix" | sed 's,S,K,g')
      if [ "$showColors" -eq 1 ]; then
        [ "$getPrefix" = "$toPrefixDis" ] && echo -e " The service ${red}$1${reset} is ALREADY EXCLUDED from startup" && return 0
      else
        [ "$getPrefix" = "$toPrefixDis" ] && echo -e " The service $1 is ALREADY EXCLUDED from startup" && return 0
      fi
      _control "$1" stop
      mv -f "$pathServices/${getPrefix}$1"  "$pathServices/${toPrefixDis}$1"
      if [ -e "$pathServices/${toPrefixDis}$1" ]; then
        if [ "$showColors" -eq 1 ]; then
          echo -e " The service ${red}$1${reset} has been removed from startup" && return 0
        else
          echo -e " The service $1 has been removed from startup" && return 0
        fi
      else
        echo -e " Failed to disable service $1" && return 255
      fi
#      return 1
    fi
    if [ "$2" = "enable" ]; then
      toPrefixEn=$(echo "$getPrefix" | sed 's,K,S,g')
      if [ "$showColors" -eq 1 ]; then
        [ "$getPrefix" = "$toPrefixEn" ] && echo -e " The service ${green}$1${reset} has ALREADY BEEN ADDED to startup" && return 0
      else
        echo -e " The service $1 has ALREADY BEEN ADDED to startup" && return 0
      fi
      _control "$1" start
      mv -f "$pathServices/${getPrefix}$1"  "$pathServices/${toPrefixEn}$1"
      if [ -e "$pathServices/${toPrefixEn}$1" ]; then
        if [ "$showColors" -eq 1 ]; then
          echo -e " The service ${green}$1${reset} has been added to startup" && return 0
        else
          echo -e " The service $1 has been added to startup" && return 0
        fi
      else
        echo -e " Failed to disable service $1" && return 255
      fi
#      return 0
    fi
#    return 1
    if [ "$2" = "edit" ]; then
      if [ -n "$(which nano)" ]; then
        editor="nano"
        $editor "$pathServices/$getPrefix$1"
        return 0
      elif [ -n "$(which vi)" ]; then
        editor="busybox vi"
        $editor "$pathServices/$getPrefix$1"
        return 0
      else
        echo -e "\nEDITOR: vi or nano NOT FOUND\n"
        return 255
      fi
      #"$editor" "$pathServices/$getPrefix$1"
      #return 0
    fi
  fi

 _control "$@"

}

service "$@"
